# Site settings
name: Matteo Conti
title: Matteo Conti | Developer & AI Student
description: Full-Stack developer and Artificial Intelligence student.
url: https://contimatteo.github.io/
baseurl: ''
email: matte.conti@icloud.com
cover: ''
logo: ''
resume: "#"
social:
  - title: email
    url: mailto:matte.conti@icloud.com
  - title: github
    url: https://github.com/contimatteo
  - title: linkedin
    url: https://www.linkedin.com/in/conti-matteo

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
