# Site settings
name: Conti Matteo
title: Conti Matteo | Front End Software Engineer
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://contimatteo.github.io/
baseurl: ''
email: matte.conti@icloud.com
cover: https://contimatteo.github.io/img/og.png
logo: https://contimatteo.github.io/img/emojis/technologist.png
resume: https://contimatteo.github.io/resume.pdf
social:
  - title: email
    url: mailto:matte.conti@icloud.com
  - title: github
    url: https://github.com/contimatteo
  - title: linkedin
    url: https://www.linkedin.com/in/conti-matteo

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
